# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  backend:
    build: .
    # entrypoint: ./init.sh
    # command: /venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 2 --loop uvloop
    command: sleep infinity
    container_name: job-seekr-finder-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - local-dev-net
    volumes:
      - .:/build

  postgres_db:
    image: postgres:17
    container_name: job-seekr-postgresql-dev-db
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE__PORT}:5432"
    networks:
      - local-dev-net

networks:
  local-dev-net:
