# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: lint, format, and unit tests check
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event.label.name == 'build' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==2.1.3
        poetry self add poetry-plugin-export
        poetry export --with dev -o /requirements.txt --without-hashes
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Formatting and linting check
      run: |
        # check formatting & linting
        ruff check --exclude "alembic/*,app/schemas/*,__init__.py"
    - name: Test with pytest
      run: |
        pytest
